chore: fix docker file
Newer hwdata-pci and kmod available in base image

[2/2] STEP 2/5: RUN apk add --no-cache kmod=30-r3 hwdata-pci=0.370-r0
fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  hwdata-pci-0.390-r0:
    breaks: world[hwdata-pci=0.370-r0]
  kmod-33-r2:
    breaks: world[kmod=30-r3]
Error: building at STEP "RUN apk add --no-cache kmod=30-r3 hwdata-pci=0.370-r0": while running runtime: exit status 2

Signed-off-by: Fred Rolland <frolland@nvidia.com>